### PR TITLE
Initial version of an examples collection

### PR DESCRIPTION
**Pull request by uruuru**
See the screenshot below. The idea is to have a page holding a collection of examples that illustrate how ELK algorithms can be configured. In particular for often-used/requested configuration options. 

The example information (and the left-side navigation) is extracted fully automatically from the description in the included `*.elkt` files. The plan is to move these examples into ELK's models repository in a next step. All that's necessary to add a new example is to push a new `elkt` file then. 

Note that I also moved some parts of the code that is used for multiple demonstrators into a `common` folder. I plan to adjust the other demonstrators after this has been merged. 

image

### CODE REVIEW

**Comment by uruuru** [comment]
> allowing the categories to be collapsed and expanded.

Definitely, I briefly looked at what bootstrap offers but didn't find something that works off-the-shelf. Hence, I postponed it.

**Comment by le-cds** [comment]
> Definitely, I briefly looked at what bootstrap offers but didn't find something that works off-the-shelf. Hence, I postponed it.

Perfectly fine. I think this is an excellent addition as it is. I also mentioned it at the group meeting, and people were thrilled. 🙂 My vote: MERGE AND DEPLOY!

**Comment by uruuru** [comment]
I'll wait another day or two - maybe Miro finds time to have a look at point out everything I did wrongly :).

**Comment by spoenemann** [comment]
> maybe Miro finds time

Not really, but I think one approving review is sufficient ;-)

**Pull request merged**
